# -*- coding: utf-8 -*-
{
    'name': 'The Earth',
    'version': '18.0.1.0.7',
    'summary': 'Manage bookings & cancellations for Hotels, Flights, Trains, Buses, Cars, Insurance, Visa, Package Tours & Events',
    'category': 'Services/Travel',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'contacts', 'sale_management', 'purchase', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/service_charge_data.xml',
        'data/hide_menus.xml',
        'report/booking_annexure_report.xml',
        'report/booking_annexure_action.xml',
        'report/debit_note_report.xml',
        'report/debit_note_template.xml',
        'wizard/hotel_booking_export_views.xml',
        'wizard/bus_booking_export_views.xml',
        'wizard/train_booking_export_views.xml',
        'wizard/domestic_flight_export_views.xml',
        'wizard/intl_flight_export_views.xml',
        'wizard/car_booking_export_views.xml',
        'wizard/insurance_booking_export_views.xml',
        'wizard/visa_booking_export_views.xml',
        'wizard/package_tour_export_views.xml',
        'wizard/event_booking_export_views.xml',
        'wizard/hotel_cancellation_export_views.xml',
        'wizard/bus_cancellation_export_views.xml',
        'wizard/train_cancellation_export_views.xml',
        'wizard/domestic_flight_cancellation_export_views.xml',
        'wizard/intl_flight_cancellation_export_views.xml',
        'wizard/insurance_cancellation_export_views.xml',
        'wizard/visa_cancellation_export_views.xml',
        'wizard/service_invoice_wizard_views.xml',
        'wizard/debit_credit_note_wizard_views.xml',
        'views/hotel_booking_views.xml',
        'views/domestic_flight_booking_views.xml',
        'views/international_flight_booking_views.xml',
        'views/train_booking_views.xml',
        'views/bus_booking_views.xml',
        'views/car_booking_views.xml',
        'views/insurance_booking_views.xml',
        'views/visa_booking_views.xml',
        'views/package_tour_booking_views.xml',
        'views/event_booking_views.xml',
        'views/cancellation_views.xml',
        'views/bus_cancellation_views.xml',
        'views/domestic_flight_cancellation_views.xml',
        'views/hotel_cancellation_views.xml',
        'views/intl_flight_cancellation_views.xml',
        'views/train_cancellation_views.xml',
        'views/insurance_cancellation_views.xml',
        'views/visa_cancellation_views.xml',
        'views/service_charge_views.xml',
        'views/sale_purchase_buttons.xml',
        'views/account_move_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [
        'demo/hotel_booking_demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'travel_booking_management/static/src/dashboard/**/*',
        ],
    },
    'installable': True,
    'application': True,
    'post_init_hook': '_hide_orphan_menus',
}
