# -*- coding: utf-8 -*-
{
    'name': 'Travel Booking Management',
    'version': '18.0.1.0.1',
    'summary': 'Manage bookings & cancellations for Hotels, Flights, Trains, Buses, Cars, Insurance, Visa, Package Tours & Events',
    'category': 'Services/Travel',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'wizard/hotel_booking_export_views.xml',
        'wizard/bus_booking_export_views.xml',
        'wizard/train_booking_export_views.xml',
        'views/hotel_booking_views.xml',
        'views/domestic_flight_booking_views.xml',
        'views/international_flight_booking_views.xml',
        'views/train_booking_views.xml',
        'views/bus_booking_views.xml',
        'views/car_booking_views.xml',
        'views/insurance_booking_views.xml',
        'views/visa_booking_views.xml',
        'views/package_tour_booking_views.xml',
        'views/event_booking_views.xml',
        'views/cancellation_views.xml',
        'views/bus_cancellation_views.xml',
        'views/domestic_flight_cancellation_views.xml',
        'views/hotel_cancellation_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
